kind: pipeline
name: kmd

environment:
steps:
- name: start
  image: fr3akyphantom/droid-builder:latest
  user: root
  environment:
    BOT_TOKEN:
      from_secret: BOT_TOKEN
    SF_PASS:
      from_secret: SF_PASS
    CLONE_PRIV:
      from_secret: CLONE_PRIV
  commands:
  - rm -rf *
  - wget https://raw.githubusercontent.com/rzlamrr/scripts/master/kmd.sh
  - wget https://raw.githubusercontent.com/fakhiralkda/komodoci/main/cloner.py
  - chmod +x kmd.sh cloner.py
  - echo $(command -v ccache)
